---
- name: Configuración de la instancia Proxy
  hosts: proxy_nat
  become: yes
  tasks:
    - name: Actualizar el índice de repositorios (apt update)
      apt:
        update_cache: yes
        
    - name: Instalar los paquetes necesarios para configurar el proxy
      apt:
        name:
          - git
          - nginx-full
          - php
          - ansible
          - iptables-persistent
          - certbot
        state: present

  ## Configuración de la instancia NAT

    - name: IPForwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
 
    - name: Crear directorio
      file:
        path: /etc/iptables
        state: directory
        mode: '0755'
 
    - name: Configurar iptables
      shell: 
        sudo iptables -t nat -A POSTROUTING -o ens5 -j MASQUERADE
 
    - name: "Guardar reglas de iptables para que se apliquen al reiniciar"
      shell: 
        iptables-save > /etc/iptables/rules.v4

    - name: Habilitar el reenvío IPv4 al iniciar la instancia
      command: echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf  

    ## Configuración del proxy inverso con Nginx

    - name: Clonar el respositorio de Fatgram
      git:
        repo: 'https://github.com/Gabriel221011/FATGRAM.git'
        dest: /home/ubuntu/FATGRAM
        version: main

    - name: Copiar el archivo de configuración de Nginx para Fatgram
      copy:
        src: /home/ubuntu/FATGRAM/Servidor Web/Proxy/
        dest: /etc/nginx/
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
    
    - name: Borrar el index.html por defecto de Nginx
      file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Habilitar el sitio de Nginx para Fatgram
      file:
        src: /etc/nginx/sites-available/proxy.conf
        dest: /etc/nginx/sites-enabled/proxy.conf
        state: link
        force: yes
    
    - name: Copia de los archivos de letsencrypt para HTTPS
      copy:
        src: /home/ubuntu/FATGRAM/Servidor Web/letsencrypt/
        dest: /etc/letsencrypt/
        owner: root
        group: root
        mode: '0644'
        remote_src: yes

    - name: Deshabilitar apache2 para evitar conflictos con Nginx
      service:
        name: apache2
        state: stopped
        enabled: no

    - name: Reiniciar Nginx para aplicar los cambios
      service:
        name: nginx
        state: restarted

    - name: Directorio para el script de configuración de los servidores
      file:
        path: /home/ubuntu/server_config
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copiar Ansible de los servidores
      copy:
        src: /home/ubuntu/FATGRAM/Scripts/Ansible/Servidores/
        dest: /home/ubuntu/server_config/
        owner: ubuntu
        group: ubuntu
        mode: '0755'
        remote_src: yes

    - name: Borrado del repositorio clonado para liberar espacio
      file:
        path: /home/ubuntu/FATGRAM
        state: absent

    ## Handlers para reiniciar el servicio de Nginx cuando se cambie su configuración
  handlers:
    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted